version: '3'

services:

  amazerrific:
   image: mongo_nodejs_image
   ports:
     - 8888
   environment:
     - SERVICE_PORTS=8888
   deploy:
     replicas: 5
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web
   depends_on:
     - mongo

  mongo:
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - '27018:27017'
    networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - amazerrific
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay


